# Generated by Django 4.1.3 on 2022-11-04 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="books",
        ),
        migrations.AddField(
            model_name="book",
            name="reviews",
            field=models.ManyToManyField(related_name="books", to="core.review"),
        ),
    ]
