# Generated by Django 4.1.3 on 2022-11-05 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_book_author_alter_book_favorites_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="name",
            field=models.CharField(default="book_name", max_length=250),
        ),
    ]
