# Generated by Django 4.1.3 on 2022-11-05 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_book_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="name",
            field=models.CharField(max_length=250),
        ),
    ]
