# Generated by Django 4.1.3 on 2022-11-05 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_book_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genre",
            name="name",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FANTASY", "FANTASY"),
                    ("DETECTIVES", "DETECTIVES"),
                    ("HORROR", "HORROR"),
                    ("ADVENTURES", "ADVENTURES"),
                    ("POETRY", "POETRY"),
                    ("LOVE_NOVELS", "LOVE_NOVELS"),
                    ("THRILLERS", "THRILLERS"),
                    ("COMICS AND MANGA", "COMICS AND MANGA"),
                    ("PROSE", "PROSE"),
                    ("BUSINESS LITERATURE", "BUSINESS LITERATURE"),
                    ("PSYCHOLOGY", "PSYCHOLOGY"),
                    ("ART AND CULTURE", "ART AND CULTURE"),
                    ("SCIENTIFIC LITERATURE", "SCIENTIFIC LITERATURE"),
                    ("HOBBIES AND LEISURE", "HOBBIES AND LEISURE"),
                    ("LEARNING LANGUAGES", "LEARNING LANGUAGES"),
                    ("STORY", "STORY"),
                    ("COMPUTER LITERATURE", "COMPUTER LITERATURE"),
                    ("BOOKS FOR PRESCHOOLERS", "BOOKS FOR PRESCHOOLERS"),
                    ("CHILDREN'S DETECTIVES", "CHILDREN'S DETECTIVES"),
                    ("CHILDRENS ADVENTURE BOOKS", "CHILDRENS ADVENTURE BOOKS"),
                    ("BOOKS FOR TEENAGERS", "BOOKS FOR TEENAGERS"),
                ],
                default="POETRY",
                max_length=250,
                unique=True,
            ),
        ),
    ]
