GENRE_TYPE_FANTASY = "FANTASY"
GENRE_TYPE_DETECTIVES = "DETECTIVES "
GENRE_TYPE_HORROR = "HORROR"
GENRE_TYPE_ADVENTURES = "ADVENTURES"
GENRE_TYPE_POETRY = "POETRY"
GENRE_TYPE_LOVE_NOVELS = "LOVE_NOVELS"
GENRE_TYPE_THRILLERS = "THRILLERS"
GENRE_TYPE_COMICS_AND_MANGA = "COMICS AND MANGA"
GENRE_TYPE_PROSE = "PROSE"
GENRE_TYPE_BUSINESS_LITERATURE = "BUSINESS LITERATURE"
GENRE_TYPE_PSYCHOLOGY = "PSYCHOLOGY"
GENRE_TYPE_ART_AND_CULTURE = "ART AND CULTURE"
GENRE_TYPE_SCIENTIFIC_LITERATURE = "SCIENTIFIC LITERATURE"
GENRE_TYPE_HOBBIES_AND_LEISURE = "HOBBIES AND LEISURE"
GENRE_TYPE_LEARNING_LANGUAGES = "LEARNING LANGUAGES"
GENRE_TYPE_STORY = "STORY"
GENRE_TYPE_COMPUTER_LITERATURE = "COMPUTER LITERATURE"
GENRE_TYPE_BOOKS_FOR_PRESCHOOLERS = "BOOKS FOR PRESCHOOLERS"
GENRE_TYPE_CHILDRENS_DETECTIVES = "CHILDREN'S DETECTIVES"
GENRE_TYPE_CHILDREN_ADVENTURE_BOOKS = "CHILDRENS ADVENTURE BOOKS"
GENRE_TYPE_BOOKS_FOR_TEENAGERS = "BOOKS FOR TEENAGERS"


GENRE_TYPE = (
     (GENRE_TYPE_FANTASY, "FANTASY"),
     (GENRE_TYPE_DETECTIVES, "DETECTIVES "),
     (GENRE_TYPE_HORROR, "HORROR"),
     (GENRE_TYPE_ADVENTURES, "ADVENTURES"),
     (GENRE_TYPE_POETRY, "POETRY"),
     (GENRE_TYPE_LOVE_NOVELS, "LOVE_NOVELS"),
     (GENRE_TYPE_THRILLERS, "THRILLERS"),
     (GENRE_TYPE_COMICS_AND_MANGA, "COMICS AND MANGA"),
     (GENRE_TYPE_PROSE, "PROSE"),
     (GENRE_TYPE_BUSINESS_LITERATURE, "BUSINESS LITERATURE"),
     (GENRE_TYPE_PSYCHOLOGY, "PSYCHOLOGY"),
     (GENRE_TYPE_ART_AND_CULTURE, "ART AND CULTURE"),
     (GENRE_TYPE_SCIENTIFIC_LITERATURE, "SCIENTIFIC LITERATURE"),
     (GENRE_TYPE_HOBBIES_AND_LEISURE, "HOBBIES AND LEISURE"),
     (GENRE_TYPE_LEARNING_LANGUAGES, "LEARNING LANGUAGES"),
     (GENRE_TYPE_STORY, "STORY"),
     (GENRE_TYPE_COMPUTER_LITERATURE, "COMPUTER LITERATURE"),
     (GENRE_TYPE_BOOKS_FOR_PRESCHOOLERS, "BOOKS FOR PRESCHOOLERS"),
     (GENRE_TYPE_CHILDRENS_DETECTIVES, "CHILDREN'S DETECTIVES"),
     (GENRE_TYPE_CHILDREN_ADVENTURE_BOOKS, "CHILDRENS ADVENTURE BOOKS"),
     (GENRE_TYPE_BOOKS_FOR_TEENAGERS, "BOOKS FOR TEENAGERS")
)
